### ISSUE TITLE
What supporting libraries are we using?

### ISSUE THREAD

**Issue by sashaweiss** [natasha-codes/snek#1]
Options include:
- [`tui-rs`](https://github.com/fdehau/tui-rs)
  - Low-level, close to the terminal
- [`termion`](https://github.com/redox-os/termion)
  - High-level TUI layout engine
  - Supports animation, complex shapes, composition, constraints
  - Can rely on multiple terminal-drawing backends, including `tui-rs`
- [`termbox`](https://github.com/nsf/termbox)
  - Text-based TUIs

possibly helpful refs:

- http://ticki.github.io/blog/making-terminal-applications-in-rust-with-termion/

**Comment by sashaweiss** [comment]
I'm gonna go ahead and suggest we use `termion`:

Pros:
- The high-level layouts will be nice for the relatively complex shapes we're gonna have
- It'll be nice to not have to manage an animation loop ourselves
- I have some experience with it from [syncterm](https://github.com/sashaweiss/syncterm), from the Rust class

Cons:
- Some overhead is inevitable
- We'll have to work within the constraints of the framework, i.e. there may be issues or incompatibilities

Responses to cons:
- Doubt that the overhead will be perceptible
- Building our own rendering framework would be 10x more work than the game itself
- If we *really* want to cut the dependency, we can definitely do it later

**Comment by sashaweiss** [comment]
@nathanshelly if you are chill with this, please move to reviewed/done

**Comment by nathanshelly** [comment]
sgtm
